# coding: utf-8

"""
    Rekor

    Rekor is a cryptographically secure, immutable transparency log for signed software releases.  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class SearchLogQuery(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'entry_uuids': 'list[str]',
        'log_indexes': 'list[int]',
        'entries': 'list[ProposedEntry]'
    }

    attribute_map = {
        'entry_uuids': 'entryUUIDs',
        'log_indexes': 'logIndexes',
        'entries': 'entries'
    }

    def __init__(self, entry_uuids=None, log_indexes=None, entries=None):  # noqa: E501
        """SearchLogQuery - a model defined in Swagger"""  # noqa: E501
        self._entry_uuids = None
        self._log_indexes = None
        self._entries = None
        self.discriminator = None
        if entry_uuids is not None:
            self.entry_uuids = entry_uuids
        if log_indexes is not None:
            self.log_indexes = log_indexes
        if entries is not None:
            self.entries = entries

    @property
    def entry_uuids(self):
        """Gets the entry_uuids of this SearchLogQuery.  # noqa: E501


        :return: The entry_uuids of this SearchLogQuery.  # noqa: E501
        :rtype: list[str]
        """
        return self._entry_uuids

    @entry_uuids.setter
    def entry_uuids(self, entry_uuids):
        """Sets the entry_uuids of this SearchLogQuery.


        :param entry_uuids: The entry_uuids of this SearchLogQuery.  # noqa: E501
        :type: list[str]
        """

        self._entry_uuids = entry_uuids

    @property
    def log_indexes(self):
        """Gets the log_indexes of this SearchLogQuery.  # noqa: E501


        :return: The log_indexes of this SearchLogQuery.  # noqa: E501
        :rtype: list[int]
        """
        return self._log_indexes

    @log_indexes.setter
    def log_indexes(self, log_indexes):
        """Sets the log_indexes of this SearchLogQuery.


        :param log_indexes: The log_indexes of this SearchLogQuery.  # noqa: E501
        :type: list[int]
        """

        self._log_indexes = log_indexes

    @property
    def entries(self):
        """Gets the entries of this SearchLogQuery.  # noqa: E501


        :return: The entries of this SearchLogQuery.  # noqa: E501
        :rtype: list[ProposedEntry]
        """
        return self._entries

    @entries.setter
    def entries(self, entries):
        """Sets the entries of this SearchLogQuery.


        :param entries: The entries of this SearchLogQuery.  # noqa: E501
        :type: list[ProposedEntry]
        """

        self._entries = entries

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(SearchLogQuery, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, SearchLogQuery):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
