# coding: utf-8

"""
    Rekor

    Rekor is a cryptographically secure, immutable transparency log for signed software releases.  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import rekor_sdk
from rekor_sdk.api.tlog_api import TlogApi  # noqa: E501
from rekor_sdk.rest import ApiException


class TestTlogApi(unittest.TestCase):
    """TlogApi unit test stubs"""

    def setUp(self):
        self.api = TlogApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_log_info(self):
        """Test case for get_log_info

        Get information about the current state of the transparency log  # noqa: E501
        """
        pass

    def test_get_log_proof(self):
        """Test case for get_log_proof

        Get information required to generate a consistency proof for the transparency log  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
