# coding: utf-8

"""
    Rekor

    Rekor is a cryptographically secure, immutable transparency log for signed software releases.  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import rekor_sdk
from rekor_sdk.api.entries_api import EntriesApi  # noqa: E501
from rekor_sdk.rest import ApiException


class TestEntriesApi(unittest.TestCase):
    """EntriesApi unit test stubs"""

    def setUp(self):
        self.api = EntriesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_log_entry(self):
        """Test case for create_log_entry

        Creates an entry in the transparency log  # noqa: E501
        """
        pass

    def test_get_log_entry_by_index(self):
        """Test case for get_log_entry_by_index

        Retrieves an entry and inclusion proof from the transparency log (if it exists) by index  # noqa: E501
        """
        pass

    def test_get_log_entry_by_uuid(self):
        """Test case for get_log_entry_by_uuid

        Get log entry and information required to generate an inclusion proof for the entry in the transparency log  # noqa: E501
        """
        pass

    def test_search_log_query(self):
        """Test case for search_log_query

        Searches transparency log for one or more log entries  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
