# coding: utf-8

"""
    Rekor

    Rekor is a cryptographically secure, immutable transparency log for signed software releases.  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import rekor_sdk
from rekor_sdk.api.index_api import IndexApi  # noqa: E501
from rekor_sdk.rest import ApiException


class TestIndexApi(unittest.TestCase):
    """IndexApi unit test stubs"""

    def setUp(self):
        self.api = IndexApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_search_index(self):
        """Test case for search_index

        Searches index by entry metadata  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
