# coding: utf-8

"""
    Rekor

    Rekor is a cryptographically secure, immutable transparency log for signed software releases.  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import rekor_sdk
from rekor_sdk.models.search_index_public_key import SearchIndexPublicKey  # noqa: E501
from rekor_sdk.rest import ApiException


class TestSearchIndexPublicKey(unittest.TestCase):
    """SearchIndexPublicKey unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSearchIndexPublicKey(self):
        """Test SearchIndexPublicKey"""
        # FIXME: construct object with mandatory attributes with example values
        # model = rekor_sdk.models.search_index_public_key.SearchIndexPublicKey()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
